### ISSUE TITLE
Mapamental Conjuntos y sub. (Resubido)

### ISSUE THREAD

**Issue by Marvinjaelhernandezgonzalez** [SistemasTecTlaxiaco/mapa-mental-Marvinjaelhernandezgonzalez#2]
[MATEMATICAS DISCRETAS.docx](https://github.com/SistemasTecTlaxiaco/mapa-mental-Marvinjaelhernandezgonzalez/files/7341544/MATEMATICAS.DISCRETAS.docx)

**Comment by 71santiago7** [comment]
20%
excelente trabajo

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
